Adding notebook
spaceml-org/helionb-geoeff pull request #1
Opened 2021-11-24 15:28 UTC by Vishal-Upendran

Notebook has been updated with comments, and public data+repo. Not tested on colab yet.

2021-11-24 16:08 UTC, PaulJWright requested changes

2021-11-24 16:08 UTC, PaulJWright commented on notebooks/01_geoeff_2020/requirements.txt
> +jupyter==4.7.1
This errors locally here. Can you confirm that this is correct?

2021-11-24 16:08 UTC, PaulJWright commented on notebooks/01_geoeff_2020/requirements.txt
> +sklearn==0.24.2
I think you need `scikit-learn` here?

2021-11-24 16:08 UTC, PaulJWright commented on notebooks/01_geoeff_2020/requirements.txt
> +PIL==8.3.1
`Pillow==` ?

2021-11-24 16:10 UTC, PaulJWright commented
For local development, a replacement to `gsutil` could be something along the lines of:

```python

def list_files(bucket, folder):
    """
    List all files in GCP bucket.
    """
    files = bucket.list_blobs(prefix=folder)
    fileList = [file.name for file in files if "." in file.name]
    return fileList
    
bucket_name= "storm_subset"
storage_client = storage.Client.create_anonymous_client()
bucket = storage_client.bucket(bucket_name)

bucket_dirs = ["2011/","2015/","model/Best/"]

for bucket_dir in bucket_dirs:

    # create folder if it doesn't exist
    if not os.path.exists(os.path.join(bucket_name, bucket_dir)):
        os.makedirs(os.path.join(bucket_name, bucket_dir))
    
    # list files
    files = list_files(bucket, bucket_dir)

    for file in files:
        blob = bucket.blob(file)
        blob.download_to_filename(os.path.join(bucket_name,file))
        print(f"downloaded {file}")
```
and adding `google.cloud` as a requirement

2021-11-24 16:37 UTC, PaulJWright commented
The Figures are great! I think that for the notebook the default should be an in-notebook animation (not an `.mp4`, and for that, the figure size needs to be greatly reduced).

Once these changes have been made, happy to approve

2021-11-25 03:50 UTC, Vishal-Upendran commented on notebooks/01_geoeff_2020/requirements.txt
> +jupyter==4.7.1
I think I will just remove jupyter, since we are running on colab anyway.

2021-11-25 03:51 UTC, Vishal-Upendran commented on notebooks/01_geoeff_2020/requirements.txt
> +sklearn==0.24.2
Oops my bad. Yes, changed.

2021-11-25 03:58 UTC, Vishal-Upendran commented
So the snippet here: https://colab.research.google.com/notebooks/snippets/gcs.ipynb#scrollTo=f8LMNz9SR0Iz , which is given by google, tells us gsutil can work in principle. Let me check if that is the case.

2021-11-25 04:38 UTC, Vishal-Upendran commented
Okay so doesn't seem to be as trivial. For now, I am using `!gsutil cp -r gs://storm_subset/ Storm/` to get stuff checked on colab, but feel free to update the code.

2021-11-25 04:59 UTC, Vishal-Upendran commented
On colab: RuntimeError: CUDA out of memory. Tried to allocate 2.97 GiB (GPU 0; 11.17 GiB total capacity; 6.22 GiB already allocated; 2.87 GiB free; 7.85 GiB reserved in total by PyTorch)

This is during the forward pass - maybe you can make an instance with more GPU capacity?

The colab I am using is this: https://colab.research.google.com/github/spaceml-org/helionb-geoeff/blob/vishal-edits/notebooks/01_geoeff_2020/storm_forecast.ipynb

2021-11-25 11:33 UTC, PaulJWright commented
Looks good. Just testing now.

2021-11-25 11:39 UTC, PaulJWright commented
Comments on the notebook:

* In the 3rd code block you're already in the directory you're trying to navigate to and it errors?
* I get the following error from the imports:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-6e4d10d2feb6> in <module>()
      1 import sys
----> 2 from dataloader import SuperMAGIAGADataset,OMNIDataset,ShpericalHarmonicsDatasetBucketized
      3 from utils.data_utils import get_omni_data,get_iaga_data_as_list
      4 from utils.splitter import generate_indices
      5 from utils.plot import SqueezedNorm

7 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/computation/check.py in <module>()
      1 from pandas.compat._optional import import_optional_dependency
      2 
----> 3 ne = import_optional_dependency("numexpr", errors="warn")
      4 NUMEXPR_INSTALLED = ne is not None
      5 if NUMEXPR_INSTALLED:

TypeError: import_optional_dependency() got an unexpected keyword argument 'errors'
```

2021-11-25 11:44 UTC, Vishal-Upendran commented
Try restarting the kernel importing all packages.

2021-11-25 12:24 UTC, PaulJWright commented
I am also getting:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-24-a58d8f63820c> in <module>()
----> 1 dbh_pred_.shape,dbh_targ.shape

NameError: name 'dbh_pred_' is not defined
```

when trying to print that shape, but I think you can just remove that cell?

2021-11-25 12:54 UTC, Vishal-Upendran commented
> when trying to print that shape, but I think you can just remove that cell?
Yes. It should be `dbh_pred.shape`, there seems to be an extra underscore.

> celluloid wasn't installed, so I think you need to pip install that at the top
I thought that was added in requirements.txt. Will update and push.

> I reduced the batch size to 850 to remove that memory issue and seems fine, but a higher number may also work.
Great!

Did you make the changes in the notebook or in the colab?

2021-11-25 14:22 UTC, PaulJWright commented
> 

Sorry, I made them in my local version

2021-11-25 14:24 UTC, Vishal-Upendran commented
No worries. I have updated the notebook, and it has rendered the first two plots fine. And batch size = 500 with 4 workers worked in the end :/

2021-11-25 14:29 UTC, PaulJWright commented
Great, feel free to merge (but please squash commits)

2021-11-25 14:32 UTC, Vishal-Upendran commented
https://colab.research.google.com/github/spaceml-org/helionb-geoeff/blob/vishal-edits/notebooks/01_geoeff_2020/storm_forecast.ipynb#scrollTo=9lPf80tIgR0I

Code works!

2021-11-25 14:34 UTC, merged